INSERT INTO ITEMS(KATEGORIA , NAZWA, CENA) VALUES ('OWOCE',' CYTRYNA', 7);

INSERT INTO ITEMS(KATEGORIA , NAZWA, CENA) VALUES ('OWOCE',' BANANY', 4);

INSERT INTO ITEMS(KATEGORIA , NAZWA, CENA) VALUES ('CHEMIA',' VIZIR', 25);

INSERT INTO ITEMS(KATEGORIA , NAZWA, CENA) VALUES ('NABIAL',' MLEKO', 9);